parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  browser: true
plugins:
  - svelte3
extends:
  - airbnb-base
  - prettier
settings:
  import/resolver:
    node:
      extensions: ['.mjs', '.js', '.svelte', '.json']
rules:
  no-use-before-define: off
  no-return-assign: off
  consistent-return: off
  import/prefer-default-export: off
overrides:
  - files: ['**/*.svelte']
    processor: svelte3/svelte3
    rules:
      prefer-const: off
      no-undef-init: off
      # disable these rules for svelte files
      # see: https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md#eslint-plugin-import
      import/first: off
      import/no-duplicates: off
      import/no-mutable-exports: off
