language: node_js
node_js:
  - 10
cache: yarn
script:
#  - yarn style:check
#  - yarn lint
  - yarn build
deploy:
  provider: s3
  local_dir: public
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: linkedup.sfbw.io
  region: us-west-2
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
