language: node_js
node_js:
  - 10
cache: yarn
env:
  IPFS_DEPLOY_PINATA__API_KEY: 0eec05c095a1cf6df916
script:
  - yarn style:check
  - yarn lint
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export SANDBOX_MODE=true; fi
  - yarn build
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(release|master)$
