language: node_js
node_js:
  - 10
cache: yarn
env:
  IPFS_DEPLOY_PINATA__API_KEY: 0eec05c095a1cf6df916
before_install:
  - npm install -g yarn@latest
script:
  - yarn build
deploy:
  provider: script
  script: yarn deploy
  on:
    branch: master
